#!/bin/sh
# Debian wrapper for the Bun-compiled Pi standalone executable.
# User configuration and state live in ~/.pi by default (override with
# PI_CODING_AGENT_DIR).
unset BUN_BE_BUN
export PI_CODING_AGENT=1
exec /usr/lib/pi/pi "$@"
